// Spotify API integration
import { type Track } from './types';

export type Mood = 'romantic' | 'sad' | 'happy' | 'motivational' | 'party';

const ROMANTIC_TRACKS: Track[] = [
  {
    id: 'r1',
    name: 'Tum Hi Ho',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Aashiqui 2',
      images: [{ url: 'https://images.pexels.com/photos/1644616/pexels-photo-1644616.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 269000,
  },
  {
    id: 'r2',
    name: 'Gerua',
    artists: [{ name: 'Arijit Singh, Antara Mitra' }],
    album: {
      name: 'Dilwale',
      images: [{ url: 'https://images.pexels.com/photos/1644617/pexels-photo-1644617.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 'r3',
    name: 'Tera Yaar Hoon Main',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Sonu Ke Titu Ki Sweety',
      images: [{ url: 'https://images.pexels.com/photos/1644618/pexels-photo-1644618.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 265000,
  },
  {
    id: 'r4',
    name: 'Raabta',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Agent Vinod',
      images: [{ url: 'https://images.pexels.com/photos/1644619/pexels-photo-1644619.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 274000,
  },
  {
    id: 'r5',
    name: 'Hawayein',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Jab Harry Met Sejal',
      images: [{ url: 'https://images.pexels.com/photos/1644620/pexels-photo-1644620.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 289000,
  },
  {
    id: 'r6',
    name: 'Tum Hi Ho Bandhu',
    artists: [{ name: 'Neeraj Shridhar, Kavita Seth' }],
    album: {
      name: 'Cocktail',
      images: [{ url: 'https://images.pexels.com/photos/1644621/pexels-photo-1644621.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 274000,
  },
  {
    id: 'r7',
    name: 'Tum Se Hi',
    artists: [{ name: 'Mohit Chauhan' }],
    album: {
      name: 'Jab We Met',
      images: [{ url: 'https://images.pexels.com/photos/1644622/pexels-photo-1644622.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 285000,
  },
  {
    id: 'r8',
    name: 'Tere Sang Yaara',
    artists: [{ name: 'Atif Aslam' }],
    album: {
      name: 'Rustom',
      images: [{ url: 'https://images.pexels.com/photos/1644623/pexels-photo-1644623.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 278000,
  },
  {
    id: 'r9',
    name: 'Mere Naam Tu',
    artists: [{ name: 'Abhay Jodhpurkar' }],
    album: {
      name: 'Zero',
      images: [{ url: 'https://images.pexels.com/photos/1644624/pexels-photo-1644624.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 295000,
  },
  {
    id: 'r10',
    name: 'Kaise Hua',
    artists: [{ name: 'Vishal Mishra' }],
    album: {
      name: 'Kabir Singh',
      images: [{ url: 'https://images.pexels.com/photos/1644625/pexels-photo-1644625.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 283000,
  },
  {
    id: 'r11',
    name: 'Tera Ban Jaunga',
    artists: [{ name: 'Tulsi Kumar, Akhil Sachdeva' }],
    album: {
      name: 'Kabir Singh',
      images: [{ url: 'https://images.pexels.com/photos/1644626/pexels-photo-1644626.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 'r12',
    name: 'Bekhayali',
    artists: [{ name: 'Sachet Tandon' }],
    album: {
      name: 'Kabir Singh',
      images: [{ url: 'https://images.pexels.com/photos/1644627/pexels-photo-1644627.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 289000,
  },
  {
    id: 'r13',
    name: 'Tujhe Kitna Chahne Lage',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Kabir Singh',
      images: [{ url: 'https://images.pexels.com/photos/1644628/pexels-photo-1644628.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 274000,
  },
  {
    id: 'r14',
    name: 'Kalank Title Track',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Kalank',
      images: [{ url: 'https://images.pexels.com/photos/1644629/pexels-photo-1644629.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 285000,
  },
  {
    id: 'r15',
    name: 'Ve Maahi',
    artists: [{ name: 'Arijit Singh, Asees Kaur' }],
    album: {
      name: 'Kesari',
      images: [{ url: 'https://images.pexels.com/photos/1644630/pexels-photo-1644630.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 268000,
  },
  {
    id: 'r16',
    name: 'Tera Fitoor',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Genius',
      images: [{ url: 'https://images.pexels.com/photos/1644631/pexels-photo-1644631.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 279000,
  },
  {
    id: 'r17',
    name: 'Dil Diyan Gallan',
    artists: [{ name: 'Atif Aslam' }],
    album: {
      name: 'Tiger Zinda Hai',
      images: [{ url: 'https://images.pexels.com/photos/1644632/pexels-photo-1644632.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 'r18',
    name: 'Main Tera Boyfriend',
    artists: [{ name: 'Arijit Singh, Neha Kakkar' }],
    album: {
      name: 'Raabta',
      images: [{ url: 'https://images.pexels.com/photos/1644633/pexels-photo-1644633.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 275000,
  },
  {
    id: 'r19',
    name: 'Humsafar',
    artists: [{ name: 'Akhil Sachdeva' }],
    album: {
      name: 'Badrinath Ki Dulhania',
      images: [{ url: 'https://images.pexels.com/photos/1644634/pexels-photo-1644634.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 'r20',
    name: 'Nashe Si Chadh Gayi',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Befikre',
      images: [{ url: 'https://images.pexels.com/photos/1644635/pexels-photo-1644635.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 283000,
  },
  {
    id: 'r21',
    name: 'Enna Sona',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'OK Jaanu',
      images: [{ url: 'https://images.pexels.com/photos/1644636/pexels-photo-1644636.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 277000,
  },
  {
    id: 'r22',
    name: 'Channa Mereya',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/1644637/pexels-photo-1644637.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 291000,
  },
  {
    id: 'r23',
    name: 'Bolna',
    artists: [{ name: 'Arijit Singh, Asees Kaur' }],
    album: {
      name: 'Kapoor & Sons',
      images: [{ url: 'https://images.pexels.com/photos/1644638/pexels-photo-1644638.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 286000,
  },
  {
    id: 'r24',
    name: 'Soch Na Sake',
    artists: [{ name: 'Arijit Singh, Tulsi Kumar' }],
    album: {
      name: 'Airlift',
      images: [{ url: 'https://images.pexels.com/photos/1644639/pexels-photo-1644639.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 288000,
  },
  {
    id: 'r25',
    name: 'Sanam Re',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Sanam Re',
      images: [{ url: 'https://images.pexels.com/photos/1644640/pexels-photo-1644640.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 279000,
  },
  {
    id: 'r26',
    name: 'Main Rahoon Ya Na Rahoon',
    artists: [{ name: 'Armaan Malik' }],
    album: {
      name: 'Main Rahoon Ya Na Rahoon',
      images: [{ url: 'https://images.pexels.com/photos/1644641/pexels-photo-1644641.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 282000,
  },
  {
    id: 'r27',
    name: 'Khamoshiyan',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Khamoshiyan',
      images: [{ url: 'https://images.pexels.com/photos/1644642/pexels-photo-1644642.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 275000,
  },
  {
    id: 'r28',
    name: 'Jeena Jeena',
    artists: [{ name: 'Atif Aslam' }],
    album: {
      name: 'Badlapur',
      images: [{ url: 'https://images.pexels.com/photos/1644643/pexels-photo-1644643.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 'r29',
    name: 'Sawan Aaya Hai',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Creature 3D',
      images: [{ url: 'https://images.pexels.com/photos/1644644/pexels-photo-1644644.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 278000,
  },
  {
    id: 'r30',
    name: 'Mast Magan',
    artists: [{ name: 'Arijit Singh, Chinmayi Sripada' }],
    album: {
      name: '2 States',
      images: [{ url: 'https://images.pexels.com/photos/1644645/pexels-photo-1644645.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 276000,
  }
];

const SAD_TRACKS: Track[] = [
  {
    id: 's1',
    name: 'Channa Mereya',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 289000,
  },
  {
    id: 's2',
    name: 'Agar Tum Saath Ho',
    artists: [{ name: 'Arijit Singh, Alka Yagnik' }],
    album: {
      name: 'Tamasha',
      images: [{ url: 'https://images.pexels.com/photos/1105667/pexels-photo-1105667.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 341000,
  },
  {
    id: 's3',
    name: 'Kabira',
    artists: [{ name: 'Arijit Singh, Harshdeep Kaur' }],
    album: {
      name: 'Yeh Jawaani Hai Deewani',
      images: [{ url: 'https://images.pexels.com/photos/1105668/pexels-photo-1105668.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 278000,
  },
  {
    id: 's4',
    name: 'Phir Le Aya Dil',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Barfi!',
      images: [{ url: 'https://images.pexels.com/photos/1105669/pexels-photo-1105669.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 268000,
  },
  {
    id: 's5',
    name: 'Ae Dil Hai Mushkil',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/1105670/pexels-photo-1105670.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 295000,
  },
  {
    id: 's6',
    name: 'Tum Hi Ho Bandhu',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Aashiqui 2',
      images: [{ url: 'https://images.pexels.com/photos/1105671/pexels-photo-1105671.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 289000,
  },
  {
    id: 's7',
    name: 'Tujhe Bhula Diya',
    artists: [{ name: 'Mohit Chauhan, Shekhar Ravjiani' }],
    album: {
      name: 'Anjaana Anjaani',
      images: [{ url: 'https://images.pexels.com/photos/1105672/pexels-photo-1105672.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 292000,
  },
  {
    id: 's8',
    name: 'Tum Mile',
    artists: [{ name: 'Neeraj Shridhar' }],
    album: {
      name: 'Tum Mile',
      images: [{ url: 'https://images.pexels.com/photos/1105673/pexels-photo-1105673.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 276000,
  },
  {
    id: 's9',
    name: 'Judaai',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Badlapur',
      images: [{ url: 'https://images.pexels.com/photos/1105674/pexels-photo-1105674.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 285000,
  },
  {
    id: 's10',
    name: 'Phir Bhi Tumko Chahunga',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Half Girlfriend',
      images: [{ url: 'https://images.pexels.com/photos/1105675/pexels-photo-1105675.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 283000,
  },
  {
    id: 's11',
    name: 'Hamari Adhuri Kahani',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Hamari Adhuri Kahani',
      images: [{ url: 'https://images.pexels.com/photos/1105676/pexels-photo-1105676.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 's12',
    name: 'Muskurane',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'CityLights',
      images: [{ url: 'https://images.pexels.com/photos/1105677/pexels-photo-1105677.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 289000,
  },
  {
    id: 's13',
    name: 'Humdard',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Ek Villain',
      images: [{ url: 'https://images.pexels.com/photos/1105678/pexels-photo-1105678.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 269000,
  },
  {
    id: 's14',
    name: 'Aayat',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Bajirao Mastani',
      images: [{ url: 'https://images.pexels.com/photos/1105679/pexels-photo-1105679.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 287000,
  },
  {
    id: 's15',
    name: 'Laal Ishq',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Goliyon Ki Raasleela Ram-Leela',
      images: [{ url: 'https://images.pexels.com/photos/1105680/pexels-photo-1105680.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 291000,
  },
  {
    id: 's16',
    name: 'Dil Sambhal Ja Zara',
    artists: [{ name: 'Mohammed Irfan' }],
    album: {
      name: 'Murder 2',
      images: [{ url: 'https://images.pexels.com/photos/1105681/pexels-photo-1105681.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 275000,
  },
  {
    id: 's17',
    name: 'Tera Chehra',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Sanam Teri Kasam',
      images: [{ url: 'https://images.pexels.com/photos/1105682/pexels-photo-1105682.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 's18',
    name: 'Duaa',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Shanghai',
      images: [{ url: 'https://images.pexels.com/photos/1105683/pexels-photo-1105683.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 268000,
  },
  {
    id: 's19',
    name: 'Bhula Dena',
    artists: [{ name: 'Mustafa Zahid' }],
    album: {
      name: 'Aashiqui 2',
      images: [{ url: 'https://images.pexels.com/photos/1105684/pexels-photo-1105684.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 273000,
  },
  {
    id: 's20',
    name: 'Ek Dil Ek Jaan',
    artists: [{ name: 'Shivam Pathak' }],
    album: {
      name: 'Padmaavat',
      images: [{ url: 'https://images.pexels.com/photos/1105685/pexels-photo-1105685.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 286000,
  },
  {
    id: 's21',
    name: 'Alvida',
    artists: [{ name: 'KK' }],
    album: {
      name: 'Life in a... Metro',
      images: [{ url: 'https://images.pexels.com/photos/1105686/pexels-photo-1105686.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 272000,
  },
  {
    id: 's22',
    name: 'Tera Hone Laga Hoon',
    artists: [{ name: 'Atif Aslam, Alisha Chinai' }],
    album: {
      name: 'Ajab Prem Ki Ghazab Kahani',
      images: [{ url: 'https://images.pexels.com/photos/1105687/pexels-photo-1105687.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 279000,
  },
  {
    id: 's23',
    name: 'Dil Diyan Gallan',
    artists: [{ name: 'Atif Aslam' }],
    album: {
      name: 'Tiger Zinda Hai',
      images: [{ url: 'https://images.pexels.com/photos/1105688/pexels-photo-1105688.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 's24',
    name: 'Phir Mohabbat',
    artists: [{ name: 'Mohammed Irfan, Arijit Singh, Saim Bhat' }],
    album: {
      name: 'Murder 2',
      images: [{ url: 'https://images.pexels.com/photos/1105689/pexels-photo-1105689.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 287000,
  },
  {
    id: 's25',
    name: 'Ek Villain Theme',
    artists: [{ name: 'Mithoon' }],
    album: {
      name: 'Ek Villain',
      images: [{ url: 'https://images.pexels.com/photos/1105690/pexels-photo-1105690.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 268000,
  },
  {
    id: 's26',
    name: 'Tujhe Sochta Hoon',
    artists: [{ name: 'KK, Tulsi Kumar' }],
    album: {
      name: 'Jannat 2',
      images: [{ url: 'https://images.pexels.com/photos/1105691/pexels-photo-1105691.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 275000,
  },
  {
    id: 's27',
    name: 'Humnava',
    artists: [{ name: 'Papon' }],
    album: {
      name: 'Hamari Adhuri Kahani',
      images: [{ url: 'https://images.pexels.com/photos/1105692/pexels-photo-1105692.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 281000,
  },
  {
    id: 's28',
    name: 'Dil Kyun Yeh Mera',
    artists: [{ name: 'KK' }],
    album: {
      name: 'Kites',
      images: [{ url: 'https://images.pexels.com/photos/1105693/pexels-photo-1105693.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 273000,
  },
  {
    id: 's29',
    name: 'Tera Mera Rishta',
    artists: [{ name: 'Mustafa Zahid' }],
    album: {
      name: 'Awarapan',
      images: [{ url: 'https://images.pexels.com/photos/1105694/pexels-photo-1105694.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 277000,
  },
  {
    id: 's30',
    name: 'Khuda Jaane',
    artists: [{ name: 'KK, Shilpa Rao' }],
    album: {
      name: 'Bachna Ae Haseeno',
      images: [{ url: 'https://images.pexels.com/photos/1105695/pexels-photo-1105695.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 285000,
  }
];

const HAPPY_TRACKS: Track[] = [
  {
    id: 'h1',
    name: 'Badtameez Dil',
    artists: [{ name: 'Benny Dayal' }],
    album: {
      name: 'Yeh Jawaani Hai Deewani',
      images: [{ url: 'https://images.pexels.com/photos/2833037/pexels-photo-2833037.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 256000,
  },
  {
    id: 'h2',
    name: 'London Thumakda',
    artists: [{ name: 'Labh Janjua, Neha Kakkar, Sonu Kakkar' }],
    album: {
      name: 'Queen',
      images: [{ url: 'https://images.pexels.com/photos/2833038/pexels-photo-2833038.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 243000,
  },
  {
    id: 'h3',
    name: 'Kar Gayi Chull',
    artists: [{ name: 'Badshah, Neha Kakkar' }],
    album: {
      name: 'Kapoor & Sons',
      images: [{ url: 'https://images.pexels.com/photos/2833039/pexels-photo-2833039.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'h4',
    name: 'Gallan Goodiyaan',
    artists: [{ name: 'Yashita Sharma, Manish Kumar Tipu, Farhan Akhtar' }],
    album: {
      name: 'Dil Dhadakne Do',
      images: [{ url: 'https://images.pexels.com/photos/2833040/pexels-photo-2833040.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 248000,
  },
  {
    id: 'h5',
    name: 'Ainvayi Ainvayi',
    artists: [{ name: 'Salim Merchant, Sunidhi Chauhan' }],
    album: {
      name: 'Band Baaja Baaraat',
      images: [{ url: 'https://images.pexels.com/photos/2833041/pexels-photo-2833041.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 251000,
  },
  {
    id: 'h6',
    name: 'Balam Pichkari',
    artists: [{ name: 'Vishal Dadlani, Shalmali Kholgade' }],
    album: {
      name: 'Yeh Jawaani Hai Deewani',
      images: [{ url: 'https://images.pexels.com/photos/2833042/pexels-photo-2833042.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 242000,
  },
  {
    id: 'h7',
    name: 'Dil Dhadakne Do',
    artists: [{ name: 'Shankar Mahadevan, Sukhwinder Singh' }],
    album: {
      name: 'Zindagi Na Milegi Dobara',
      images: [{ url: 'https://images.pexels.com/photos/2833043/pexels-photo-2833043.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 256000,
  },
  {
    id: 'h8',
    name: 'Ullu Ka Pattha',
    artists: [{ name: 'Arijit Singh, Nikhita Gandhi' }],
    album: {
      name: 'Jagga Jasoos',
      images: [{ url: 'https://images.pexels.com/photos/2833044/pexels-photo-2833044.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 249000,
  },
  {
    id: 'h9',
    name: 'Tune Maari Entriyaan',
    artists: [{ name: 'Vishal Dadlani, Bappi Lahiri' }],
    album: {
      name: 'Gunday',
      images: [{ url: 'https://images.pexels.com/photos/2833045/pexels-photo-2833045.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 245000,
  },
  {
    id: 'h10',
    name: 'Nachde Ne Saare',
    artists: [{ name: 'Jasleen Royal, Harshdeep Kaur' }],
    album: {
      name: 'Baar Baar Dekho',
      images: [{ url: 'https://images.pexels.com/photos/2833046/pexels-photo-2833046.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 239000,
  },
  {
    id: 'h11',
    name: 'Cutiepie',
    artists: [{ name: 'Pardeep Singh Sran, Nakash Aziz' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/2833047/pexels-photo-2833047.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 237000,
  },
  {
    id: 'h12',
    name: 'Kala Chashma',
    artists: [{ name: 'Badshah, Neha Kakkar, Amar Arshi' }],
    album: {
      name: 'Baar Baar Dekho',
      images: [{ url: 'https://images.pexels.com/photos/2833048/pexels-photo-2833048.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 241000,
  },
  {
    id: 'h13',
    name: 'Breakup Song',
    artists: [{ name: 'Nakash Aziz, Arijit Singh, Badshah, Jonita Gandhi' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/2833049/pexels-photo-2833049.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 244000,
  },
  {
    id: 'h14',
    name: 'Chittiyaan Kalaiyaan',
    artists: [{ name: 'Meet Bros, Kanika Kapoor' }],
    album: {
      name: 'Roy',
      images: [{ url: 'https://images.pexels.com/photos/2833050/pexels-photo-2833050.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'h15',
    name: 'Abhi Toh Party Shuru Hui Hai',
    artists: [{ name: 'Badshah, Aastha' }],
    album: {
      name: 'Khoobsurat',
      images: [{ url: 'https://images.pexels.com/photos/2833051/pexels-photo-2833051.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 236000,
  },
  {
    id: 'h16',
    name: 'Desi Girl',
    artists: [{ name: 'Vishal Dadlani, Shankar Mahadevan, Sunidhi Chauhan' }],
    album: {
      name: 'Dostana',
      images: [{ url: 'https://images.pexels.com/photos/2833052/pexels-photo-2833052.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 252000,
  },
  {
    id: 'h17',
    name: 'Dhoom Machale',
    artists: [{ name: 'Sunidhi Chauhan' }],
    album: {
      name: 'Dhoom',
      images: [{ url: 'https://images.pexels.com/photos/2833053/pexels-photo-2833053.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 247000,
  },
  {
    id: 'h18',
    name: 'Pappu Cant Dance',
    artists: [{ name: 'Benny Dayal, Neeraj Shridhar' }],
    album: {
      name: 'Jaane Tu... Ya Jaane Na',
      images: [{ url: 'https://images.pexels.com/photos/2833054/pexels-photo-2833054.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 243000,
  },
  {
    id: 'h19',
    name: 'Its The Time To Disco',
    artists: [{ name: 'KK, Vasundhara Das' }],
    album: {
      name: 'Kal Ho Naa Ho',
      images: [{ url: 'https://images.pexels.com/photos/2833055/pexels-photo-2833055.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 246000,
  },
  {
    id: 'h20',
    name: 'Mauja Hi Mauja',
    artists: [{ name: 'Mika Singh' }],
    album: {
      name: 'Jab We Met',
      images: [{ url: 'https://images.pexels.com/photos/2833056/pexels-photo-2833056.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 244000,
  },
  {
    id: 'h21',
    name: 'Aaj Ki Party',
    artists: [{ name: 'Mika Singh' }],
    album: {
      name: 'Bajrangi Bhaijaan',
      images: [{ url: 'https://images.pexels.com/photos/2833057/pexels-photo-2833057.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 235000,
  },
  {
    id: 'h22',
    name: 'Dard-E-Disco',
    artists: [{ name: 'Sukhwinder Singh' }],
    album: {
      name: 'Om Shanti Om',
      images: [{ url: 'https://images.pexels.com/photos/2833058/pexels-photo-2833058.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 249000,
  },
  {
    id: 'h23',
    name: 'Dhating Naach',
    artists: [{ name: 'Nakash Aziz, Neha Kakkar' }],
    album: {
      name: 'Phata Poster Nikhla Hero',
      images: [{ url: 'https://images.pexels.com/photos/2833059/pexels-photo-2833059.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 242000,
  },
  {
    id: 'h24',
    name: 'Chammak Challo',
    artists: [{ name: 'Akon, Hamsika Iyer' }],
    album: {
      name: 'Ra.One',
      images: [{ url: 'https://images.pexels.com/photos/2833060/pexels-photo-2833060.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'h25',
    name: 'Subah Hone Na De',
    artists: [{ name: 'Mika Singh, Shefali Alvares' }],
    album: {
      name: 'Desi Boyz',
      images: [{ url: 'https://images.pexels.com/photos/2833061/pexels-photo-2833061.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 241000,
  },
  {
    id: 'h26',
    name: 'Pungi',
    artists: [{ name: 'Mika Singh, Javed Ali' }],
    album: {
      name: 'Agent Vinod',
      images: [{ url: 'https://images.pexels.com/photos/2833062/pexels-photo-2833062.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 237000,
  },
  {
    id: 'h27',
    name: 'Dil Dance Maare',
    artists: [{ name: 'Shaan, Sunidhi Chauhan' }],
    album: {
      name: 'Tashan',
      images: [{ url: 'https://images.pexels.com/photos/2833063/pexels-photo-2833063.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 245000,
  },
  {
    id: 'h28',
    name: 'Jhak Maar Ke',
    artists: [{ name: 'Neeraj Shridhar, Shreya Ghoshal' }],
    album: {
      name: 'Desi Boyz',
      images: [{ url: 'https://images.pexels.com/photos/2833064/pexels-photo-2833064.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 243000,
  },
  {
    id: 'h29',
    name: 'Ainvayi Ainvayi',
    artists: [{ name: 'Salim Merchant, Sunidhi Chauhan' }],
    album: {
      name: 'Band Baaja Baaraat',
      images: [{ url: 'https://images.pexels.com/photos/2833065/pexels-photo-2833065.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 251000,
  },
  {
    id: 'h30',
    name: 'Hadippa',
    artists: [{ name: 'Sunidhi Chauhan, Mika Singh' }],
    album: {
      name: 'Dil Bole Hadippa!',
      images: [{ url: 'https://images.pexels.com/photos/2833066/pexels-photo-2833066.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 246000,
  }
];

const MOTIVATIONAL_TRACKS: Track[] = [
  {
    id: 'm1',
    name: 'Zinda',
    artists: [{ name: 'Siddharth Mahadevan' }],
    album: {
      name: 'Bhaag Milkha Bhaag',
      images: [{ url: 'https://images.pexels.com/photos/1616470/pexels-photo-1616470.jpeg', height: 300,
      width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 262000,
  },
  {
    id: 'm2',
    name: 'Kar Har Maidaan Fateh',
    artists: [{ name: 'Sukhwinder Singh, Shreya Ghoshal' }],
    album: {
      name: 'Sanju',
      images: [{ url: 'https://images.pexels.com/photos/1616471/pexels-photo-1616471.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 282000,
  },
  {
    id: 'm3',
    name: 'Chak De India',
    artists: [{ name: 'Sukhwinder Singh' }],
    album: {
      name: 'Chak De India',
      images: [{ url: 'https://images.pexels.com/photos/1616472/pexels-photo-1616472.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 268000,
  },
  {
    id: 'm4',
    name: 'Brothers Anthem',
    artists: [{ name: 'Ajay Gogavale' }],
    album: {
      name: 'Brothers',
      images: [{ url: 'https://images.pexels.com/photos/1616473/pexels-photo-1616473.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 279000,
  },
  {
    id: 'm5',
    name: 'Sultan',
    artists: [{ name: 'Sukhwinder Singh' }],
    album: {
      name: 'Sultan',
      images: [{ url: 'https://images.pexels.com/photos/1616474/pexels-photo-1616474.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 285000,
  },
  {
    id: 'm6',
    name: 'Lakshya Ko Har Haal Mein Paana Hai',
    artists: [{ name: 'Shankar Mahadevan' }],
    album: {
      name: 'Lakshya',
      images: [{ url: 'https://images.pexels.com/photos/1616475/pexels-photo-1616475.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 278000,
  },
  {
    id: 'm7',
    name: 'Badal Pe Paon Hai',
    artists: [{ name: 'Shankar Mahadevan' }],
    album: {
      name: 'Chak De India',
      images: [{ url: 'https://images.pexels.com/photos/1616476/pexels-photo-1616476.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 267000,
  },
  {
    id: 'm8',
    name: 'Kar Har Maidaan Fateh',
    artists: [{ name: 'Sukhwinder Singh, Shreya Ghoshal' }],
    album: {
      name: 'Sanju',
      images: [{ url: 'https://images.pexels.com/photos/1616477/pexels-photo-1616477.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 282000,
  },
  {
    id: 'm9',
    name: 'Kandhon Se Milte Hain Kandhe',
    artists: [{ name: 'Sonu Nigam' }],
    album: {
      name: 'Lakshya',
      images: [{ url: 'https://images.pexels.com/photos/1616478/pexels-photo-1616478.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 276000,
  },
  {
    id: 'm10',
    name: 'Ziddi Dil',
    artists: [{ name: 'Vishal Dadlani' }],
    album: {
      name: 'Mary Kom',
      images: [{ url: 'https://images.pexels.com/photos/1616479/pexels-photo-1616479.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 'm11',
    name: 'Salaam India',
    artists: [{ name: 'Sukhwinder Singh' }],
    album: {
      name: 'Mary Kom',
      images: [{ url: 'https://images.pexels.com/photos/1616480/pexels-photo-1616480.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 274000,
  },
  {
    id: 'm12',
    name: 'Aashayein',
    artists: [{ name: 'KK' }],
    album: {
      name: 'Iqbal',
      images: [{ url: 'https://images.pexels.com/photos/1616481/pexels-photo-1616481.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 269000,
  },
  {
    id: 'm13',
    name: 'Sapna Jahan',
    artists: [{ name: 'Sonu Nigam, Neeti Mohan' }],
    album: {
      name: 'Brothers',
      images: [{ url: 'https://images.pexels.com/photos/1616482/pexels-photo-1616482.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 283000,
  },
  {
    id: 'm14',
    name: 'Jee Le Zaraa',
    artists: [{ name: 'Vishal Dadlani' }],
    album: {
      name: 'Talaash',
      images: [{ url: 'https://images.pexels.com/photos/1616483/pexels-photo-1616483.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 277000,
  },
  {
    id: 'm15',
    name: 'Kholo Kholo',
    artists: [{ name: 'Shankar Mahadevan' }],
    album: {
      name: 'Taare Zameen Par',
      images: [{ url: 'https://images.pexels.com/photos/1616484/pexels-photo-1616484.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 286000,
  },
  {
    id: 'm16',
    name: 'Dil Ye Bekarar Kyun Hai',
    artists: [{ name: 'Shreya Ghoshal' }],
    album: {
      name: 'Players',
      images: [{ url: 'https://images.pexels.com/photos/1616485/pexels-photo-1616485.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 272000,
  },
  {
    id: 'm17',
    name: 'Sadda Haq',
    artists: [{ name: 'Mohit Chauhan' }],
    album: {
      name: 'Rockstar',
      images: [{ url: 'https://images.pexels.com/photos/1616486/pexels-photo-1616486.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 288000,
  },
  {
    id: 'm18',
    name: 'Ae Raju',
    artists: [{ name: 'Vishal Dadlani, Divine' }],
    album: {
      name: 'Gully Boy',
      images: [{ url: 'https://images.pexels.com/photos/1616487/pexels-photo-1616487.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 267000,
  },
  {
    id: 'm19',
    name: 'Apna Time Aayega',
    artists: [{ name: 'Ranveer Singh' }],
    album: {
      name: 'Gully Boy',
      images: [{ url: 'https://images.pexels.com/photos/1616488/pexels-photo-1616488.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 274000,
  },
  {
    id: 'm20',
    name: 'Kar Gaye Chull',
    artists: [{ name: 'Badshah, Neha Kakkar' }],
    album: {
      name: 'Kapoor & Sons',
      images: [{ url: 'https://images.pexels.com/photos/1616489/pexels-photo-1616489.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'm21',
    name: 'Sooraj Dooba Hain',
    artists: [{ name: 'Arijit Singh, Aditi Singh Sharma' }],
    album: {
      name: 'Roy',
      images: [{ url: 'https://images.pexels.com/photos/1616490/pexels-photo-1616490.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 'm22',
    name: 'Gallan Goodiyaan',
    artists: [{ name: 'Yashita Sharma, Manish Kumar Tipu' }],
    album: {
      name: 'Dil Dhadakne Do',
      images: [{ url: 'https://images.pexels.com/photos/1616491/pexels-photo-1616491.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 248000,
  },
  {
    id: 'm23',
    name: 'Matargashti',
    artists: [{ name: 'Mohit Chauhan' }],
    album: {
      name: 'Tamasha',
      images: [{ url: 'https://images.pexels.com/photos/1616492/pexels-photo-1616492.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 'm24',
    name: 'Jeena Jeena',
    artists: [{ name: 'Atif Aslam' }],
    album: {
      name: 'Badlapur',
      images: [{ url: 'https://images.pexels.com/photos/1616493/pexels-photo-1616493.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 'm25',
    name: 'Gerua',
    artists: [{ name: 'Arijit Singh, Antara Mitra' }],
    album: {
      name: 'Dilwale',
      images: [{ url: 'https://images.pexels.com/photos/1616494/pexels-photo-1616494.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  },
  {
    id: 'm26',
    name: 'Janam Janam',
    artists: [{ name: 'Arijit Singh, Antara Mitra' }],
    album: {
      name: 'Dilwale',
      images: [{ url: 'https://images.pexels.com/photos/1616495/pexels-photo-1616495.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 275000,
  },
  {
    id: 'm27',
    name: 'Sooraj Dooba Hain',
    artists: [{ name: 'Arijit Singh, Aditi Singh Sharma' }],
    album: {
      name: 'Roy',
      images: [{ url: 'https://images.pexels.com/photos/1616496/pexels-photo-1616496.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 284000,
  },
  {
    id: 'm28',
    name: 'Tum Hi Ho',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Aashiqui 2',
      images: [{ url: 'https://images.pexels.com/photos/1616497/pexels-photo-1616497.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 269000,
  },
  {
    id: 'm29',
    name: 'Channa Mereya',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/1616498/pexels-photo-1616498.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 289000,
  },
  {
    id: 'm30',
    name: 'Ae Dil Hai Mushkil',
    artists: [{ name: 'Arijit Singh' }],
    album: {
      name: 'Ae Dil Hai Mushkil',
      images: [{ url: 'https://images.pexels.com/photos/1616499/pexels-photo-1616499.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 295000,
  }
];

const PARTY_TRACKS: Track[] = [
  {
    id: 'p1',
    name: 'Kala Chashma',
    artists: [{ name: 'Badshah, Neha Kakkar, Amar Arshi' }],
    album: {
      name: 'Baar Baar Dekho',
      images: [{ url: 'https://images.pexels.com/photos/2901581/pexels-photo-2901581.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 241000,
  },
  {
    id: 'p2',
    name: 'Kar Gayi Chull',
    artists: [{ name: 'Badshah, Neha Kakkar, Fazilpuria, Sukriti Kakar' }],
    album: {
      name: 'Kapoor & Sons',
      images: [{ url: 'https://images.pexels.com/photos/2901582/pexels-photo-2901582.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'p3',
    name: 'Saturday Saturday',
    artists: [{ name: 'Badshah, Indeep Bakshi' }],
    album: {
      name: 'Humpty Sharma Ki Dulhania',
      images: [{ url: 'https://images.pexels.com/photos/2901583/pexels-photo-2901583.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 235000,
  },
  {
    id: 'p4',
    name: 'London Thumakda',
    artists: [{ name: 'Labh Janjua, Neha Kakkar, Sonu Kakkar' }],
    album: {
      name: 'Queen',
      images: [{ url: 'https://images.pexels.com/photos/2901584/pexels-photo-2901584.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 243000,
  },
  {
    id: 'p5',
    name: 'Abhi Toh Party Shuru Hui Hai',
    artists: [{ name: 'Badshah, Aastha' }],
    album: {
      name: 'Khoobsurat',
      images: [{ url: 'https://images.pexels.com/photos/2901585/pexels-photo-2901585.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 236000,
  },
  {
    id: 'p6',
    name: 'Badtameez Dil',
    artists: [{ name: 'Benny Dayal, Shefali Alvares' }],
    album: {
      name: 'Yeh Jawaani Hai Deewani',
      images: [{ url: 'https://images.pexels.com/photos/2901586/pexels-photo-2901586.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 256000,
  },
  {
    id: 'p7',
    name: 'Malhari',
    artists: [{ name: 'Vishal Dadlani' }],
    album: {
      name: 'Bajirao Mastani',
      images: [{ url: 'https://images.pexels.com/photos/2901587/pexels-photo-2901587.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 245000,
  },
  {
    id: 'p8',
    name: 'Gallan Goodiyaan',
    artists: [{ name: 'Sukhwinder Singh, Yashita Sharma' }],
    album: {
      name: 'Dil Dhadakne Do',
      images: [{ url: 'https://images.pexels.com/photos/2901588/pexels-photo-2901588.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 248000,
  },
  {
    id: 'p9',
    name: 'Chittiyaan Kalaiyaan',
    artists: [{ name: 'Meet Bros, Kanika Kapoor' }],
    album: {
      name: 'Roy',
      images: [{ url: 'https://images.pexels.com/photos/2901589/pexels-photo-2901589.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'p10',
    name: 'Baby Ko Bass Pasand Hai',
    artists: [{ name: 'Vishal Dadlani, Shalmali Kholgade' }],
    album: {
      name: 'Sultan',
      images: [{ url: 'https://images.pexels.com/photos/2901590/pexels-photo-2901590.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 242000,
  },
  {
    id: 'p11',
    name: 'Nachan Farrate',
    artists: [{ name: 'Meet Bros, Kanika Kapoor' }],
    album: {
      name: 'All Is Well',
      images: [{ url: 'https://images.pexels.com/photos/2901591/pexels-photo-2901591.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 237000,
  },
  {
    id: 'p12',
    name: 'Tamma Tamma Again',
    artists: [{ name: 'Bappi Lahiri, Anuradha Paudwal' }],
    album: {
      name: 'Badrinath Ki Dulhania',
      images: [{ url: 'https://images.pexels.com/photos/2901592/pexels-photo-2901592.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 244000,
  },
  {
    id: 'p13',
    name: 'Kamariya',
    artists: [{ name: 'Aastha Gill, Divya Kumar' }],
    album: {
      name: 'Stree',
      images: [{ url: 'https://images.pexels.com/photos/2901593/pexels-photo-2901593.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 239000,
  },
  {
    id: 'p14',
    name: 'Dil Chori',
    artists: [{ name: 'Yo Yo Honey Singh, Simar Kaur' }],
    album: {
      name: 'Sonu Ke Titu Ki Sweety',
      images: [{ url: 'https://images.pexels.com/photos/2901594/pexels-photo-2901594.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 241000,
  },
  {
    id: 'p15',
    name: 'Chhote Chhote Peg',
    artists: [{ name: 'Yo Yo Honey Singh, Neha Kakkar' }],
    album: {
      name: 'Sonu Ke Titu Ki Sweety',
      images: [{ url: 'https://images.pexels.com/photos/2901595/pexels-photo-2901595.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 243000,
  },
  {
    id: 'p16',
    name: 'Morni Banke',
    artists: [{ name: 'Guru Randhawa, Neha Kakkar' }],
    album: {
      name: 'Badhaai Ho',
      images: [{ url: 'https://images.pexels.com/photos/2901596/pexels-photo-2901596.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 236000,
  },
  {
    id: 'p17',
    
    name: 'Aankh Marey',
    artists: [{ name: 'Neha Kakkar, Kumar Sanu' }],
    album: {
      name: 'Simmba',
      images: [{ url: 'https://images.pexels.com/photos/2901597/pexels-photo-2901597.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'p18',
    name: 'Dilbar',
    artists: [{ name: 'Neha Kakkar, Dhvani Bhanushali' }],
    album: {
      name: 'Satyameva Jayate',
      images: [{ url: 'https://images.pexels.com/photos/2901598/pexels-photo-2901598.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 242000,
  },
  {
    id: 'p19',
    name: 'Coca Cola',
    artists: [{ name: 'Tony Kakkar, Neha Kakkar' }],
    album: {
      name: 'Luka Chuppi',
      images: [{ url: 'https://images.pexels.com/photos/2901599/pexels-photo-2901599.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 235000,
  },
  {
    id: 'p20',
    name: 'Poster Lagwa Do',
    artists: [{ name: 'Mika Singh, Sunanda Sharma' }],
    album: {
      name: 'Luka Chuppi',
      images: [{ url: 'https://images.pexels.com/photos/2901600/pexels-photo-2901600.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 237000,
  },
  {
    id: 'p21',
    name: 'Nikle Currant',
    artists: [{ name: 'Jassi Gill, Neha Kakkar' }],
    album: {
      name: 'Nikle Currant',
      images: [{ url: 'https://images.pexels.com/photos/2901601/pexels-photo-2901601.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 240000,
  },
  {
    id: 'p22',
    name: 'Chalti Hai Kya 9 Se 12',
    artists: [{ name: 'Dev Negi, Neha Kakkar' }],
    album: {
      name: 'Judwaa 2',
      images: [{ url: 'https://images.pexels.com/photos/2901602/pexels-photo-2901602.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 243000,
  },
  {
    id: 'p23',
    name: 'Lift Teri Bandh Hai',
    artists: [{ name: 'Ash King, Shipra Goyal' }],
    album: {
      name: 'Judwaa 2',
      images: [{ url: 'https://images.pexels.com/photos/2901603/pexels-photo-2901603.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 238000,
  },
  {
    id: 'p24',
    name: 'Oonchi Hai Building',
    artists: [{ name: 'Anu Malik, Neha Kakkar' }],
    album: {
      name: 'Judwaa 2',
      images: [{ url: 'https://images.pexels.com/photos/2901604/pexels-photo-2901604.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 241000,
  },
  {
    id: 'p25',
    name: 'Dil Chori',
    artists: [{ name: 'Yo Yo Honey Singh, Simar Kaur' }],
    album: {
      name: 'Sonu Ke Titu Ki Sweety',
      images: [{ url: 'https://images.pexels.com/photos/2901605/pexels-photo-2901605.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 241000,
  },
  {
    id: 'p26',
    name: 'Bom Diggy Diggy',
    artists: [{ name: 'Zack Knight, Jasmin Walia' }],
    album: {
      name: 'Sonu Ke Titu Ki Sweety',
      images: [{ url: 'https://images.pexels.com/photos/2901606/pexels-photo-2901606.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 237000,
  },
  {
    id: 'p27',
    name: 'Sweety Tera Drama',
    artists: [{ name: 'Dev Negi, Pawni Pandey' }],
    album: {
      name: 'Bareilly Ki Barfi',
      images: [{ url: 'https://images.pexels.com/photos/2901607/pexels-photo-2901607.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 242000,
  },
  {
    id: 'p28',
    name: 'Twist Kamariya',
    artists: [{ name: 'Neha Kakkar, Sukriti Kakar' }],
    album: {
      name: 'Bareilly Ki Barfi',
      images: [{ url: 'https://images.pexels.com/photos/2901608/pexels-photo-2901608.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 239000,
  },
  {
    id: 'p29',
    name: 'Badri Ki Dulhania',
    artists: [{ name: 'Dev Negi, Neha Kakkar' }],
    album: {
      name: 'Badrinath Ki Dulhania',
      images: [{ url: 'https://images.pexels.com/photos/2901609/pexels-photo-2901609.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 236000,
  },
  {
    id: 'p30',
    name: 'Humsafar',
    artists: [{ name: 'Akhil Sachdeva, Mansheel Gujral' }],
    album: {
      name: 'Badrinath Ki Dulhania',
      images: [{ url: 'https://images.pexels.com/photos/2901610/pexels-photo-2901610.jpeg', height: 300, width: 300 }],
    },
    preview_url: 'https://p.scdn.co/mp3-preview/sample',
    external_urls: { spotify: 'https://open.spotify.com/track/sample' },
    duration_ms: 271000,
  }
];

export const getTracks = async (mood: Mood): Promise<Track[]> => {
  await new Promise((resolve) => setTimeout(resolve, 500)); // Simulate API delay

  switch (mood) {
    case 'romantic':
      return ROMANTIC_TRACKS;
    case 'sad':
      return SAD_TRACKS;
    case 'happy':
      return HAPPY_TRACKS;
    case 'motivational':
      return MOTIVATIONAL_TRACKS;
    case 'party':
      return PARTY_TRACKS;
    default:
      return [...ROMANTIC_TRACKS, ...SAD_TRACKS, ...HAPPY_TRACKS, ...MOTIVATIONAL_TRACKS, ...PARTY_TRACKS];
  }
};

export function msToMinutesAndSeconds(ms: number): string {
  const minutes = Math.floor(ms / 60000);
  const seconds = ((ms % 60000) / 1000).toFixed(0);
  return `${minutes}:${Number(seconds) < 10 ? '0' : ''}${seconds}`;
}