// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jydtlwzdhhtfejftrqnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5ZHRsd3pkaGh0ZmVqZnRycW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDcxMjUsImV4cCI6MjA2MDA4MzEyNX0.7MKDUd8TBniyOAlFylwb48tMssL4zES6rf7x4niapXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);